packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - expo-splash-screen@57.0.6
