/**
 * F12 — API pública del módulo de SESIONES (planificador de entrenamiento).
 */

export {
  SESSION_BLOCK_TYPES,
  DEFAULT_SESSION_SKELETON,
  SESSION_VISIBILITIES,
  buildDefaultSkeleton,
  isSessionBlockType,
  isSessionVisibility,
  canRecommend,
  isRecommendedExercise,
  sessionDateFromEventStart,
  isIsoDate,
  addDaysIso,
  mondayOfWeek,
  weekDaysIso,
  type SessionBlockType,
  type SessionVisibility,
  type SeededBlock,
  type RecommendableExercise,
  type RecommendCriteria,
} from './sessions';

export {
  sessionBlockTypeSchema,
  sessionVisibilitySchema,
  sessionHeaderSchema,
  sessionTaskSchema,
  sessionBlockSchema,
  createSessionSchema,
  updateSessionHeaderSchema,
  setSessionVisibilitySchema,
  toSessionHeaderColumns,
  addBlockTaskSchema,
  updateBlockTaskSchema,
  toTaskOverrideColumns,
  blockTaskIdSchema,
  reorderBlocksSchema,
  reorderTasksSchema,
  moveTaskSchema,
  saveAsTemplateSchema,
  createFromTemplateSchema,
  sessionIdSchema,
  planSessionForEventSchema,
  linkSessionToEventSchema,
  sumTaskMinutes,
  type SessionHeaderInput,
  type SessionTaskInput,
  type SessionBlockInput,
  type CreateSessionInput,
  type UpdateSessionHeaderInput,
  type SetSessionVisibilityInput,
  type SessionHeaderColumns,
  type AddBlockTaskInput,
  type UpdateBlockTaskInput,
  type TaskOverrideColumns,
  type BlockTaskIdInput,
  type ReorderBlocksInput,
  type ReorderTasksInput,
  type MoveTaskInput,
  type SaveAsTemplateInput,
  type CreateFromTemplateInput,
  type SessionIdInput,
  type PlanSessionForEventInput,
  type LinkSessionToEventInput,
} from './session-form';
