/**
 * F12 — API pública del módulo de SESIONES (planificador de entrenamiento).
 */

export {
  getSharedSessionsForTeamsFromClient,
  getTeamTrainingsFromClient,
  getSessionForEditFromClient,
  getSessionExerciseMetaFromClient,
  getSessionTemplatesFromClient,
  getPickableExercisesFromClient,
  getEventSessionIdFromClient,
  getPlanSessionOptionsFromClient,
} from './queries';
export type {
  PlayerSharedSessionRow,
  TeamTrainingRow,
  SessionTaskForEdit,
  SessionBlockPlayForEdit,
  SessionBlockForEdit,
  SessionForEdit,
  SessionExerciseMeta,
  SessionTemplateRow,
  PickableExercise,
  LinkableSession,
  PlanSessionOptions,
} from './queries';

export {
  planSessionForEventFromClient,
  updateSessionHeaderFromClient,
  setSessionSharedFromClient,
  addBlockTaskFromClient,
  removeBlockTaskFromClient,
  reorderTasksFromClient,
} from './plan';
export type { PlanSessionResult, SessionWriteError, AddTaskResult } from './plan';

export {
  SESSION_BLOCK_TYPES,
  DEFAULT_SESSION_SKELETON,
  SESSION_VISIBILITIES,
  buildDefaultSkeleton,
  isSessionBlockType,
  isSessionVisibility,
  canRecommend,
  isRecommendedExercise,
  sessionDateFromEventStart,
  isIsoDate,
  addDaysIso,
  mondayOfWeek,
  weekDaysIso,
  type SessionBlockType,
  type SessionVisibility,
  type SeededBlock,
  type RecommendableExercise,
  type RecommendCriteria,
} from './sessions';

export {
  sessionBlockTypeSchema,
  sessionVisibilitySchema,
  sessionHeaderSchema,
  sessionTaskSchema,
  sessionBlockSchema,
  createSessionSchema,
  updateSessionHeaderSchema,
  setSessionVisibilitySchema,
  toSessionHeaderColumns,
  addBlockTaskSchema,
  updateBlockTaskSchema,
  toTaskOverrideColumns,
  blockTaskIdSchema,
  reorderBlocksSchema,
  reorderTasksSchema,
  moveTaskSchema,
  addBlockPlaySchema,
  updateBlockPlaySchema,
  toPlayOverrideColumns,
  blockPlayIdSchema,
  reorderBlockPlaysSchema,
  saveAsTemplateSchema,
  createFromTemplateSchema,
  sessionIdSchema,
  planSessionForEventSchema,
  linkSessionToEventSchema,
  updateSessionHeaderMobileSchema,
  toSessionHeaderMobileColumns,
  sumTaskMinutes,
  type SessionHeaderInput,
  type SessionTaskInput,
  type SessionBlockInput,
  type CreateSessionInput,
  type UpdateSessionHeaderInput,
  type SetSessionVisibilityInput,
  type SessionHeaderColumns,
  type AddBlockTaskInput,
  type UpdateBlockTaskInput,
  type TaskOverrideColumns,
  type BlockTaskIdInput,
  type ReorderBlocksInput,
  type ReorderTasksInput,
  type MoveTaskInput,
  type AddBlockPlayInput,
  type UpdateBlockPlayInput,
  type PlayOverrideColumns,
  type BlockPlayIdInput,
  type ReorderBlockPlaysInput,
  type SaveAsTemplateInput,
  type CreateFromTemplateInput,
  type SessionIdInput,
  type PlanSessionForEventInput,
  type LinkSessionToEventInput,
  type UpdateSessionHeaderMobileInput,
  type SessionHeaderMobileColumns,
} from './session-form';
